(async()=>{const __user=await MFAuth.require3d();if(!__user)return;
const D=window.MF_DATA||{materials:[]},R=window.MF_RATES||{services:{}};let bodyMaterial=null,frontMaterial=null;
const q=id=>document.getElementById(id),N=MF.norm,E=MF.esc;
function score(m,s){const n=N(s),code=N(m.article||`${m.decor||''}${m.structure||''}`),h=N(`${m.manufacturer||''} ${m.article||''} ${m.decor||''} ${m.structure||''} ${m.name||''}`);let x=0;if(code===n)x+=180;if(h.includes(n))x+=50;const p=n.match(/[A-ZА-ЯЁ]+|\d+/g)||[];if(p.length&&p.every(z=>h.includes(z)))x+=35;return x}
function searchM(s){return D.materials.map(m=>({m,s:score(m,s)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,10)}
function bindSearch(inpId,resId,setter){const inp=q(inpId),res=q(resId);inp.addEventListener('input',()=>{const a=searchM(inp.value);res.innerHTML=a.map((x,i)=>`<div class="result" data-i="${i}"><strong>${E(x.m.manufacturer)} ${E(x.m.article||x.m.decor||'')}</strong><small>${E(x.m.name)} · ${x.m.sqmPrice||'—'} ${E(x.m.currency||'')}/м²</small></div>`).join('');res.classList.toggle('hidden',!a.length);res.querySelectorAll('.result').forEach((el,i)=>el.onclick=()=>{setter(a[i].m);inp.value=`${a[i].m.manufacturer||''} ${a[i].m.article||a[i].m.decor||''} — ${a[i].m.name||''}`.replace(/\s+/g,' ').trim();res.classList.add('hidden');updateAll()})})}
bindSearch('bodyMat','bodyResults',m=>bodyMaterial=m);bindSearch('frontMat','frontResults',m=>frontMaterial=m);
const canvas=q('threeCanvas'),ctx=canvas.getContext('2d');let boxes=[],rotY=-.48,rotX=.16,zoom=1,drag=false,px=0,py=0;
function colorFor(m,front=false){const s=((m?.name||'')+' '+(m?.decor||'')).toLowerCase();if(s.includes('зел'))return'#6f8976';if(s.includes('бел'))return front?'#f2efe6':'#ddd8ca';if(s.includes('сер')||s.includes('бетон'))return'#858b87';if(s.includes('чер')||s.includes('графит'))return'#424844';if(s.includes('дуб')||s.includes('орех'))return'#a77d58';if(s.includes('голуб'))return'#809ca9';return front?'#9cb883':'#b99a77'}
function addBox(w,h,d,x,y,z,color){boxes.push({w,h,d,x,y,z,color})}
function dims(){return{w:+q('widthNum').value||1000,h:+q('heightNum').value||850,d:+q('depthNum').value||450,layout:q('layoutType').value,drawers:+q('drawerCount').value||3,base:q('baseType').value,handles:q('handleType').value}}
function buildBoxes(){boxes=[];const p=dims(),S=1/350,W=p.w*S,H=p.h*S,Dp=p.d*S,t=18*S,bc=colorFor(bodyMaterial),fc=colorFor(frontMaterial,true),baseH=p.base==='plinth'?80*S:0;addBox(t,H-baseH,Dp,-W/2+t/2,baseH/2,0,bc);addBox(t,H-baseH,Dp,W/2-t/2,baseH/2,0,bc);addBox(W-2*t,t,Dp,0,H/2-t/2,0,bc);addBox(W-2*t,t,Dp,0,-H/2+baseH+t/2,0,bc);if(p.base==='plinth')addBox(W,baseH,Dp*.78,0,-H/2+baseH/2,0,bc);if(p.base==='legs'){for(const x of [-W*.38,W*.38])for(const z of [-Dp*.32,Dp*.32])addBox(t*1.8,80*S,t*1.8,x,-H/2+40*S,z,'#454a46')}const innerH=H-baseH-2*t,frontZ=Dp/2+.035,gap=.018;if(p.layout==='drawers'){const n=p.drawers,fh=(innerH-(n+1)*gap)/n;for(let i=0;i<n;i++){const y=-H/2+baseH+t+gap+fh/2+i*(fh+gap);addBox(W-2*gap,fh,.045,0,y,frontZ,fc);if(p.handles==='handles')addBox(W*.18,.025,.055,0,y,frontZ+.055,'#353936')}}else if(p.layout==='doors'){const dh=innerH-gap*2;for(const x of [-W/4,W/4]){addBox(W/2-gap*1.5,dh,.045,x,-H/2+baseH+t+dh/2+gap,frontZ,fc);if(p.handles==='handles')addBox(.025,dh*.18,.055,x+(x<0?W*.18:-W*.18),0,frontZ+.055,'#353936')}}else if(p.layout==='combo'){const topH=innerH*.42,n=Math.max(2,Math.min(3,p.drawers)),fh=(topH-(n+1)*gap)/n;for(let i=0;i<n;i++){const y=H/2-t-gap-fh/2-i*(fh+gap);addBox(W-2*gap,fh,.045,0,y,frontZ,fc);if(p.handles==='handles')addBox(W*.18,.025,.055,0,y,frontZ+.055,'#353936')}const bottomH=innerH-topH-gap*2,cy=-H/2+baseH+t+bottomH/2+gap;for(const x of [-W/4,W/4])addBox(W/2-gap*1.5,bottomH,.045,x,cy,frontZ,fc)}else{const nicheH=innerH*.35;addBox(W-2*t,t,Dp*.92,0,H/2-t-nicheH,0,bc);const bottom=innerH-nicheH-gap*2,n=Math.max(2,p.drawers),fh=(bottom-(n+1)*gap)/n;for(let i=0;i<n;i++){const y=-H/2+baseH+t+gap+fh/2+i*(fh+gap);addBox(W-2*gap,fh,.045,0,y,frontZ,fc)}}}
function hexRgb(hex){hex=hex.replace('#','');return[parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)]}
function shade(hex,f){const [r,g,b]=hexRgb(hex);return`rgb(${Math.max(0,Math.min(255,r*f))|0},${Math.max(0,Math.min(255,g*f))|0},${Math.max(0,Math.min(255,b*f))|0})`}
function transform(p){let{x,y,z}=p;const cy=Math.cos(rotY),sy=Math.sin(rotY),cx=Math.cos(rotX),sx=Math.sin(rotX);let x1=cy*x+sy*z,z1=-sy*x+cy*z,y1=cx*y-sx*z,z2=sx*y+cx*z;return{x:x1,y:y1,z:z2}}
function project(p,w,h){const t=transform(p),dist=7.2*zoom,f=4.7,sc=f/(dist-t.z),scale=Math.min(w,h)*.34;return{x:w/2+t.x*sc*scale,y:h*.52-t.y*sc*scale,z:t.z}}
function boxFaces(b){const x0=b.x-b.w/2,x1=b.x+b.w/2,y0=b.y-b.h/2,y1=b.y+b.h/2,z0=b.z-b.d/2,z1=b.z+b.d/2,v=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]].map(p=>({x:p[0],y:p[1],z:p[2]}));return[[0,1,2,3,.72],[4,5,6,7,1.05],[0,4,7,3,.84],[1,5,6,2,.92],[3,2,6,7,1.15],[0,1,5,4,.65]].map(f=>({verts:f.slice(0,4).map(i=>v[i]),shade:f[4],color:b.color}))}
function drawScene(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);const cw=r.width,ch=r.height;const grd=ctx.createLinearGradient(0,0,0,ch);grd.addColorStop(0,'#eef4ef');grd.addColorStop(1,'#dce7df');ctx.fillStyle=grd;ctx.fillRect(0,0,cw,ch);ctx.strokeStyle='rgba(73,99,80,.10)';ctx.lineWidth=1;for(let i=-6;i<=6;i++){let a=project({x:i*.5,y:-1.8,z:-3},cw,ch),b=project({x:i*.5,y:-1.8,z:3},cw,ch);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();a=project({x:-3,y:-1.8,z:i*.5},cw,ch);b=project({x:3,y:-1.8,z:i*.5},cw,ch);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}let faces=[];for(const b of boxes)faces.push(...boxFaces(b));faces.forEach(f=>{f.pp=f.verts.map(v=>project(v,cw,ch));f.depth=f.pp.reduce((s,p)=>s+p.z,0)/4});faces.sort((a,b)=>a.depth-b.depth);for(const f of faces){ctx.beginPath();ctx.moveTo(f.pp[0].x,f.pp[0].y);for(let i=1;i<4;i++)ctx.lineTo(f.pp[i].x,f.pp[i].y);ctx.closePath();ctx.fillStyle=shade(f.color,f.shade);ctx.fill();ctx.strokeStyle='rgba(25,45,31,.18)';ctx.stroke()}requestAnimationFrame(drawScene)}
function cutlist(){const p=dims(),t=18,inner=p.w-2*t,baseH=p.base==='plinth'?80:0,arr=[['Боковина',p.h-baseH,p.d,2,'корпус'],['Крышка/дно',inner,p.d,2,'корпус']];if(p.base==='plinth')arr.push(['Цоколь',p.w,p.d*.78,1,'корпус']);if(p.layout==='drawers'){const fh=Math.floor((p.h-baseH-2*t-(p.drawers+1)*3)/p.drawers);arr.push(['Фасад ящика',p.w-6,fh,p.drawers,'фасад'])}if(p.layout==='doors')arr.push(['Фасад двери',Math.floor(p.w/2)-3,p.h-baseH-2*t-6,2,'фасад']);if(p.layout==='combo'){const top=Math.floor((p.h-baseH-2*t)*.42),n=Math.max(2,Math.min(3,p.drawers));arr.push(['Фасад ящика',p.w-6,Math.floor((top-(n+1)*3)/n),n,'фасад']);arr.push(['Фасад двери',Math.floor(p.w/2)-3,p.h-baseH-2*t-top-6,2,'фасад'])}if(p.layout==='niche'){const nh=Math.floor((p.h-baseH-2*t)*.35),n=Math.max(2,p.drawers);arr.push(['Полка ниши',inner,p.d,1,'корпус']);arr.push(['Фасад ящика',p.w-6,Math.floor((p.h-baseH-2*t-nh-(n+1)*3)/n),n,'фасад'])}return arr}
function calcPrice(arr){const cut=R.services.cut18?.price||.75,pack=R.services.pack?.price||1.5;let total=0,area=0,cutm=0;for(const r of arr){const a=r[1]*r[2]/1e6*r[3];area+=a;const mat=r[4]==='фасад'?frontMaterial:bodyMaterial;if(mat?.currency==='BYN'&&mat?.sqmPrice)total+=a*mat.sqmPrice;cutm+=2*(r[1]+r[2])/1000*r[3]}total+=cutm*cut+area*pack;return{total,area,cutm}}
function updateAll(){const p=dims(),arr=cutlist();q('dimsBadge').textContent=`${p.w}×${p.h}×${p.d}`;q('layoutBadge').textContent={drawers:'только ящики',doors:'только двери',combo:'ящики + двери',niche:'ящики + ниша'}[p.layout];q('cutlist').innerHTML=`<table><thead><tr><th>Деталь</th><th>Размер</th><th>Кол.</th></tr></thead><tbody>${arr.map(r=>`<tr><td>${E(r[0])}</td><td>${Math.round(r[1])}×${Math.round(r[2])}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table>`;const c=calcPrice(arr);if(bodyMaterial&&frontMaterial){q('price').textContent=`${c.total.toFixed(2)} BYN`;q('priceNote').textContent='Материал + прямолинейный раскрой + упаковка. Кромка и фурнитура уточняются в деталировке.'}else{q('price').textContent='—';q('priceNote').textContent='Выберите материалы корпуса и фасадов.'}buildBoxes()}
for(const base of ['width','height','depth']){q(base+'Range').addEventListener('input',e=>{q(base+'Num').value=e.target.value;updateAll()});q(base+'Num').addEventListener('input',e=>{q(base+'Range').value=e.target.value;updateAll()})}for(const id of ['layoutType','drawerCount','baseType','handleType'])q(id).addEventListener('change',updateAll);canvas.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;rotY+=(e.clientX-px)*.008;rotX=Math.max(-.45,Math.min(.45,rotX+(e.clientY-py)*.004));px=e.clientX;py=e.clientY});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.6,Math.min(1.8,zoom+Math.sign(e.deltaY)*.08))},{passive:false});q('resetView').onclick=()=>{rotY=0;rotX=.08;zoom=1};
function makeGroup(material,name,rows){return{id:MF.uuid(),manualName:material?`${material.manufacturer||''} ${material.article||material.decor||''} — ${material.name||''}`.replace(/\s+/g,' ').trim():name,material,requiresApproval:!material,defaultTexture:true,edges:[],defaultEdgeId:'',details:rows.map((r,i)=>({id:MF.uuid(),toCut:true,pos:i+1,name:r[0],len:Math.round(r[1]),wid:Math.round(r[2]),qty:r[3],texture:true,canRotate:false,glue:false,l1:'',l2:'',w1:'',w2:'',comment:'Из 3D-конструктора'}))}}
q('toOrder').onclick=()=>{const arr=cutlist(),bodyRows=arr.filter(r=>r[4]==='корпус'),frontRows=arr.filter(r=>r[4]==='фасад');const mats=[makeGroup(bodyMaterial,'Корпус — материал требует выбора',bodyRows)];if(frontRows.length)mats.push(makeGroup(frontMaterial,'Фасады — материал требует выбора',frontRows));localStorage.setItem('mf_constructor_order',JSON.stringify({orderName:`Комод ${dims().w}×${dims().h}×${dims().d}`,materials:mats}));location.href='order.html'};
updateAll();drawScene();

})();
