(async()=>{const __user=await MFAuth.requireAuth();if(!__user)return;
const demo=[{id:'1',material:'EGGER H305 ST12 — Дуб Тонсберг натуральный',code:'H305 ST12',thickness:18,length:1200,width:620,qty:1,price:18,status:'В наличии',place:'Стеллаж 3'},{id:'2',material:'BYSPAN 860 PO — Бетон Спаркс лайт',code:'860 PO',thickness:18,length:850,width:410,qty:2,price:9,status:'В наличии',place:'Стеллаж 1'},{id:'3',material:'EXTRAVERT M.100.S01 — Белый облачный',code:'M.100.S01',thickness:18,length:950,width:570,qty:1,price:14,status:'В наличии',place:'Стеллаж 2'}];let scraps=demo;
const q=id=>document.getElementById(id),N=MF.norm,E=MF.esc;
function fit(r,l,w){if(!l&&!w)return true;return (r.length>=l&&r.width>=w)||(r.length>=w&&r.width>=l)}
function render(){const s=N(q('query').value),l=+q('minL').value||0,w=+q('minW').value||0,t=+q('thick').value||0;const a=scraps.filter(r=>String(r.status||'').toLowerCase().includes('налич')&&(!s||N(`${r.material} ${r.code}`).includes(s))&&(!t||+r.thickness===t)&&fit(r,l,w));q('scrapGrid').innerHTML=a.length?a.map(r=>`<article class="scrap-card"><span class="pill">${E(r.status)}</span><h3>${E(r.material)}</h3><div class="muted">${E(r.code||'')} · ${r.thickness} мм</div><div class="scrap-dim">${r.length} × ${r.width}</div><div class="scrap-meta"><span>Количество: <b>${r.qty}</b></span><span>Цена: <b>${r.price!=null?r.price+' BYN':'уточнить'}</b></span><span>Место: ${E(r.place||'—')}</span><span>ID: ${E(r.id||'—')}</span></div><button class="btn btn-primary" style="width:100%;margin-top:14px" onclick="reserve('${String(r.id).replace(/'/g,'')}')">Забронировать</button></article>`).join(''):'<div class="notice">Подходящих остатков не найдено.</div>'}
async function load(){if(window.MF_CONFIG?.backendUrl){try{const r=await fetch(MF_CONFIG.backendUrl+'?action=scraps');const j=await r.json();if(j.ok&&Array.isArray(j.items)){scraps=j.items;q('sourceBadge').textContent='Google Таблица';q('updated').textContent='обновлено '+new Date().toLocaleString('ru-RU')}}catch(e){q('sourceBadge').textContent='демо-база (сервер недоступен)'}}render()}
window.reserve=async id=>{const r=scraps.find(x=>String(x.id)===String(id));if(window.MF_CONFIG?.backendUrl){try{await fetch(MF_CONFIG.backendUrl,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'reserve',scrapId:id,phone:'',material:r?.material||''})});alert('Запрос на бронь отправлен. Мы свяжемся для подтверждения.');return}catch(e){}}alert(`Заявка на остаток ${r?.material||id} пока сохранена только как демонстрация. После подключения сервера бронь будет приходить в Telegram.`)};
['query','minL','minW','thick'].forEach(id=>q(id).addEventListener('input',render));load();

})();
