"""Generate the classic-browser data file from the API/PDF catalogue source."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]/'backend/v2/cabinet_assets/planner'
data=json.loads((root/'tall-variants.json').read_text())
(root/'tall-variants.js').write_text('/* Generated by scripts/build-tall-variants.py. */\n'+
    'globalThis.MF_TALL_VARIANTS = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n'+
    'globalThis.MF_VITRINE_VARIANTS = '+json.dumps(json.loads((root/'vitrine-variants.json').read_text()),ensure_ascii=False,separators=(',',':'))+';\n'+
    'globalThis.MF_VITRINE_LIGHTING = '+json.dumps(json.loads((root/'vitrine-lighting.json').read_text()),ensure_ascii=False,separators=(',',':'))+';\n'+
    'globalThis.MF_APPLIANCE_TALL_VARIANTS = '+json.dumps(json.loads((root/'appliance-tall-variants.json').read_text()),ensure_ascii=False,separators=(',',':'))+';\n')
