'use strict';
const $=id=>document.getElementById(id), content=$('content');
let currentUser=null;
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);if(error)$('message').focus();}
function button(text,fn,secondary=false){const e=node('button',text,secondary?'secondary':'');e.type='button';e.onclick=()=>run(async()=>{e.disabled=true;try{await fn();}finally{if(e.isConnected)e.disabled=false;}});return e;}
function value(v){return v===null||v===undefined?'Уточняется':String(v);}
function date(v){return new Date(v).toLocaleDateString('ru-RU');}
async function api(path,method='GET',body,headers={}){const r=await fetch('/api/v2'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok){const e=await r.json().catch(()=>({}));const code=e.detail?.code;const labels={LOGIN_FAILED:'Не удалось войти. Проверьте email и пароль.',EMAIL_NOT_VERIFIED:'Подтвердите email перед отправкой.',REVISION_CONFLICT:'Заказ изменился. Обновите страницу.',PROBLEMATIC_HANDOFF_REQUIRED:'Подтвердите передачу проблемных позиций менеджеру.',SOURCE_FILE_REQUIRED:'Добавьте исходный файл в подготовке заказа.',CLIENT_ACCOUNT_REQUIRED:'Этот кабинет предназначен для клиента.',VALIDATION_ERROR:'Проверьте заполненные поля.',DOCUMENT_RENDER_LIMIT:'Документ требует проверки специалистом.',DOCUMENT_INTEGRITY_FAILED:'Документ временно недоступен. Обратитесь к менеджеру.'};const err=new Error(labels[code]||workspaceErrors[code]||'Действие недоступно. Проверьте данные и доступ к заказу.');err.status=r.status;err.code=code;throw err;}return r.status===204?null:r.json();}
let busy=false;
async function run(fn){if(busy)return;busy=true;content.inert=true;content.setAttribute('aria-busy','true');try{message('Выполняется…');await fn();if($('message').textContent==='Выполняется…')message('');}catch(e){message(e.message,true);}finally{busy=false;content.inert=false;content.setAttribute('aria-busy','false');}}
async function start(){
 try{currentUser=await api('/auth/me');}catch(e){$('auth').hidden=false;$('account').hidden=true;$('logout').hidden=true;if(e.status!==401)message(e.message,true);return;}
 $('auth').hidden=true;$('account').hidden=false;$('logout').hidden=false;$('verification').hidden=currentUser.email_verified;
 const staff=!currentUser.roles.includes('client');$('staff-link').hidden=!staff;$('profile').hidden=staff;$('orders').textContent=staff?'Рабочая очередь':'Мои заказы';$('prepare-link').hidden=!currentUser.capabilities.draft_create;
 await workspaceStart();
}
async function login(register=registrationMode){if(!$('login').reportValidity())return;const f=new FormData($('login'));await api('/auth/'+(register?'register':'login'),'POST',{email:f.get('email'),password:f.get('password')});$('login').reset();await start();}
$('login').onsubmit=e=>{e.preventDefault();run(()=>login());};$('register').onclick=()=>{registrationMode=!registrationMode;authMode();};
$('logout').onclick=()=>run(async()=>{await api('/auth/logout','POST',{});content.replaceChildren();currentUser=null;await start();});
$('verify').onclick=()=>run(async()=>{await api('/auth/email-verification/request','POST',{});message('Запрос принят. В тестовой среде письмо сохраняется в закрытый тестовый приёмник; внешняя отправка отключена.');});
$('orders').onclick=()=>run(()=>currentUser.roles.includes('client')?list():staffHome());
$('profile').onclick=()=>run(async()=>{const p=await api('/account/profile');content.replaceChildren(node('h1','Данные клиента'));const f=node('form');for(const [key,label]of[['display_name','Имя клиента'],['company_name','Компания']]){const l=node('label',label),i=node('input');i.name=key;i.maxLength=200;i.value=p[key];l.append(i);f.append(l);}const save=node('button','Сохранить');f.append(save);f.onsubmit=e=>{e.preventDefault();run(async()=>{await api('/account/profile','PATCH',Object.fromEntries(new FormData(f)));message('Данные сохранены. Ранее созданные документы не изменены.');});};content.append(f);});
async function list(after='',append=false){const data=await api('/account/orders?after='+encodeURIComponent(after));if(!append){content.replaceChildren(node('h1','Мои заказы'));if(!data.items.length)content.append(node('p','Пока нет заказов. Начните с исходного Excel или создайте деталировку самостоятельно.','empty'));if(currentUser.capabilities.draft_create)content.append(link('Подготовить заказ','/editor','button'));}for(const o of data.items){const el=node('article',undefined,'order'),a=node('a',o.number+' · '+o.name);a.href='#'+o.order_id;a.onclick=e=>{e.preventDefault();run(()=>detail(o.order_id));};el.append(a,node('p',[date(o.created_at),o.preparation_label,o.status_label,o.revision_number?'Редакция '+o.revision_number:''].filter(Boolean).join(' · '),'meta'),node('p',o.amount!==null?value(o.amount)+' BYN · предварительно':o.calculation_label));content.append(el);}if(data.next){const more=button('Показать ещё',async()=>{more.remove();await list(data.next,true);},true);content.append(more);}}
async function newOrder(){content.replaceChildren(node('h1','Новый черновик'));const f=node('form'),label=node('label','Название заказа'),input=node('input');input.name='business_name';input.required=true;input.maxLength=200;label.append(input);const select=node('select');select.name='preparation_mode';for(const [v,t]of[['manager_assisted','С помощью менеджера'],['self_prepared','Самостоятельная подготовка']]){const o=node('option',t);o.value=v;select.append(o);}const modeLabel=node('label','Способ подготовки');modeLabel.append(select);f.append(label,modeLabel,node('button','Создать'));f.onsubmit=e=>{e.preventDefault();run(async()=>{const o=await api('/orders','POST',Object.fromEntries(new FormData(f)));location.assign('/editor?order='+encodeURIComponent(o.order_id));});};content.append(f);}
function table(headers,rows){const t=node('table'),head=node('tr');headers.forEach(x=>head.append(node('th',x)));const thead=node('thead');thead.append(head);t.append(thead);const body=node('tbody');rows.forEach(row=>{const tr=node('tr');row.forEach(x=>tr.append(node('td',value(x))));body.append(tr);});t.append(body);head.querySelectorAll('th').forEach(th=>th.scope='col');const wrap=node('div',undefined,'table-wrap');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Таблица — горизонтальная прокрутка');wrap.append(t);return wrap;}
async function pdf(id){const doc=await api('/calculations/'+id+'/documents/preliminary','POST',{});const a=node('a');a.href='/api/v2/documents/'+doc.file_id;a.download='';document.body.append(a);a.click();a.remove();}
async function detail(id){const o=await api('/account/orders/'+id),timeline=await api('/account/orders/'+id+'/timeline');content.replaceChildren(node('p',o.number,'eyebrow'),node('h1',o.name),node('p',[o.preparation_label,o.status_label,'Редакция '+(o.revision_number||'ещё не создана')].join(' · '),'meta'),node('p',o.next_step));if(o.problem_message)content.append(node('p',o.problem_message,'notice'));
 const actions=node('div',undefined,'actions');if(o.workflow_status==='draft'||o.status==='draft')actions.append(link('Продолжить деталировку','/editor?order='+encodeURIComponent(id),'button secondary'));if(o.calculation_id){const b=button('Скачать предварительный расчёт',()=>pdf(o.calculation_id));b.disabled=!o.can_generate;actions.append(b);}const send=button('Отправить заказ на обработку',()=>submit(o),true);send.disabled=!o.can_submit;actions.append(send);content.append(actions);
 const c=o.calculation;if(c){content.append(node('h2',c.title),node('p',c.status_label));if(c.synthetic)content.append(node('p','Тестовый пример с условными ценами.','notice'));if(c.materials.length){content.append(node('h3','Материалы'),table(['Материал / формат','Расчётное количество листов','Цена за лист, BYN','Сумма, BYN'],c.materials.map(m=>[[m.manufacturer,m.name,m.article,m.structure,m.thickness?m.thickness+' мм':'',m.length?m.length+' × '+m.width+' мм':''].filter(Boolean).join(' · '),m.quantity,m.unit_price,m.amount])));if(c.materials.some(m=>m.supply_source==='customer'))content.append(node('p',c.customer_material_notice,'notice'));}if(c.edges.length)content.append(node('h3','Материал кромки'),table(['Кромка','Чистовой метраж, м','Оплачиваемый метраж, м','Цена / м, BYN','Сумма, BYN'],c.edges.map(e=>[[e.name||e.designation,e.article,e.width+' × '+e.thickness+' мм'].filter(Boolean).join(' · '),e.net_metres,e.billable_metres,e.unit_price,e.amount])));if(c.services.length)content.append(node('h3','Производственные услуги'),table(['Операция','Объём','Тариф, BYN','Сумма, BYN'],c.services.map(s=>[s.name,value(s.quantity)+' '+({m:'м',m2:'м²'}[s.unit]||''),s.unit_price,s.amount])));content.append(node('h3','Три независимые скидки'),table(['Категория','До скидки','Скидка, %','Скидка, BYN','После, BYN'],c.discounts.map(d=>[d.name,d.gross,d.percent,d.discount,d.net])));if(c.unresolved.length){const ul=node('ul');c.unresolved.forEach(x=>ul.append(node('li',x)));content.append(node('h3','Требует уточнения стоимости'),ul);}content.append(node('h3',c.amount_label),node('p',c.amount===null?'Уточняется':value(c.amount)+' BYN','amount'),node('p',c.disclaimer,'muted'));}else{content.append(node('h2',o.calculation_label));if(o.materials.length)content.append(table(['Материалы'],o.materials.map(m=>[[m.name,m.article].filter(Boolean).join(' · ')])));}
 content.append(node('h2','Документы'));if(!o.documents.length)content.append(node('p','Документы ещё не сформированы.','muted'));for(const d of o.documents){const p=node('p'),a=node('a',d.name+(d.document_version?' · версия '+d.document_version:'')+' · '+date(d.created_at));a.href=d.download_url;p.append(a);content.append(p);}if(o.calculations.length){content.append(node('h2','История расчётов'));for(const calc of o.calculations){const row=node('p','Редакция '+calc.revision_number+' · '+date(calc.created_at)+' · '+(calc.amount===null?'Требует уточнения стоимости':value(calc.amount)+' BYN')+' ');if(calc.can_generate)row.append(button('Скачать эту версию',()=>pdf(calc.calculation_id),true));content.append(row);}}
 await orderFiles(id);
 content.append(node('h2','История заказа'));const history=node('ol',undefined,'timeline');timeline.items.forEach(x=>history.append(node('li',date(x.date)+' · '+x.label)));content.append(history);
}
async function submit(o){content.replaceChildren(node('h1','Передать заказ на обработку'),node('p','Проверьте комментарий. Передача сохраняет текущую редакцию и направляет её менеджеру для проверки.'));const f=node('form'),label=node('label','Комментарий менеджеру'),text=node('textarea');text.name='comment';text.maxLength=2000;text.required=o.preparation_mode==='manager_assisted';if(text.required)text.minLength=10;label.append(text);f.append(label);let check=null;if(['invalid','needs_confirmation','incomplete'].includes(o.calculation_state)){const l=node('label','Передать позиции, требующие уточнения, на проверку менеджеру');check=node('input');check.type='checkbox';l.append(check);f.append(l);}f.append(node('button','Подтвердить отправку'));const key=crypto.randomUUID();f.onsubmit=e=>{e.preventDefault();run(async()=>{const body={comment:text.value,handoff_problematic:check?.checked||false};if(o.revision_id)body.revision_id=o.revision_id;if(o.calculation_id)body.preliminary_calculation_id=o.calculation_id;await api('/orders/'+o.order_id+'/submit','POST',body,{'If-Match':String(o.optimistic_lock_version),'Idempotency-Key':key});await detail(o.order_id);message('Заказ передан на обработку.');});};content.append(f,button('Назад к заказу',()=>detail(o.order_id),true));}
window.addEventListener('DOMContentLoaded',()=>{authMode();run(start);});
