'use strict';
// Presentation adapters only. Prices, catalogue identity, validation and gates remain server-owned.
const workspaceErrors={PERMISSION_DENIED:'Недостаточно прав для этого действия.',AUTH_REQUIRED:'Войдите в кабинет. Несохранённые поля остаются на странице.',BAZIS_RUN_REQUIRED:'Итоговый расчёт ещё не подтверждён производством.',BAZIS_CALIBRATION_REQUIRED:'Производственная проверка пока недоступна.',APPROVED_FINAL_REQUIRED:'Нужен согласованный итоговый расчёт.',DRAFT_REQUIRED:'Редактирование этого черновика уже закрыто.',PARENT_REVISION_CONFLICT:'Редакция изменилась. Откройте актуальную версию; ваши поля не сброшены.',EXACT_RELEASED_ITEM_REQUIRED:'Выберите точный материал из закреплённого каталога.',CATALOGUE_NOT_PUBLISHED:'Каталог пока не опубликован. Попробуйте позже.',TEMPLATE_OR_SHEET_MISMATCH:'Лист или заголовки не совпали с шаблоном. Проверьте настройки импорта.',INVALID_OR_UNSAFE_XLSX:'Не удалось прочитать XLSX. Проверьте формат файла.',STAFF_NOT_FOUND:'Сотрудник не найден.',SUBMITTED_REQUIRED:'В проверку можно взять только отправленный заказ.'};
let registrationMode=location.pathname.startsWith('/register');
function authMode(){$('auth-submit').textContent=registrationMode?'Создать аккаунт':'Войти';$('form-title').textContent=registrationMode?'Регистрация':'Войти в кабинет';$('register').textContent=registrationMode?'У меня есть аккаунт':'Зарегистрироваться';$('password').autocomplete=registrationMode?'new-password':'current-password';$('password').minLength=registrationMode?12:1;}
function link(text,href,cls){const a=node('a',text,cls);a.href=href;return a;}
function field(label,name,type='text',val='',required=false){const l=node('label',label),i=node(type==='textarea'?'textarea':'input');i.name=name;i.id='f-'+crypto.randomUUID();l.htmlFor=i.id;if(type!=='textarea')i.type=type;i.value=val??'';i.required=required;i.maxLength=type==='textarea'?4000:200;l.append(i);return [l,i];}
function selectField(label,name,options,val){const l=node('label',label),s=node('select');s.name=name;s.id='s-'+crypto.randomUUID();l.htmlFor=s.id;for(const [v,t]of options){const o=node('option',t);o.value=v;s.append(o);}if(val!==undefined)s.value=val;l.append(s);return[l,s];}
function heading(text,note){content.replaceChildren(node('p','Martin Forest / Рабочее пространство','eyebrow'),node('h1',text));if(note)content.append(node('p',note,'muted'));document.title=text+' | Martin Forest';}
function confirmAction(title,description){return new Promise(resolve=>{const d=node('dialog'),h=node('h2',title),p=node('p',description),actions=node('div',undefined,'actions');const yes=node('button','Подтвердить'),no=node('button','Отмена','secondary');actions.append(no,yes);d.append(h,p,actions);d.setAttribute('aria-label',title);let done=false;function close(v){if(done)return;done=true;d.close();d.remove();resolve(v);}yes.onclick=()=>close(true);no.onclick=()=>close(false);d.oncancel=e=>{e.preventDefault();close(false);};document.body.append(d);d.showModal();no.focus();});}
async function workspaceStart(){
 const path=location.pathname;
 if(path==='/constructor.html'){heading('3D-конструктор','Отдельный рабочий инструмент');content.append(node('p','В этой версии кабинета подключение проектов и подписки 3D ещё не завершено. Доступ к рабочему инструменту временно закрыт.','notice'),link('Подготовить деталировку','/order/','button'));return;}
 if(path==='/staff'||path==='/admin.html'){await staffHome();return;}
 if(path==='/editor'||path==='/order.html'){await editorStart();return;}
 if(!currentUser.roles.includes('client')){await staffHome();return;}
 if(location.hash&&/^[0-9a-f-]{36}$/.test(location.hash.slice(1)))await detail(location.hash.slice(1));else await list();
}
const statusLabels={draft:'Черновик',submitted:'Передан на обработку',review:'На проверке',awaiting_approval:'Ожидает согласования',approved:'Согласован',production:'В производстве',completed:'Завершён',cancelled:'Отменён'};
let editorOrder=null,manualRows=[],catalogueRelease=null,dirty=false,importId=null,activeRow=null,revisionComment="";
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function editorStart(){
 const id=new URLSearchParams(location.search).get('order');
 if(!id){heading('Начните с заказа','Название поможет найти деталировку в кабинете.');const form=node('form',undefined,'panel');const [l,n]=field('Название заказа','business_name','text','',true);const [ml,m]=selectField('Способ подготовки','preparation_mode',[['manager_assisted','С помощью менеджера'],['self_prepared','Самостоятельно']],new URLSearchParams(location.search).get('mode')==='self'?'self_prepared':'manager_assisted');form.append(l,ml,node('button','Создать черновик'));form.onsubmit=e=>{e.preventDefault();run(async()=>{const o=await api('/orders','POST',{business_name:n.value,preparation_mode:m.value});history.replaceState(null,'','/editor?order='+encodeURIComponent(o.order_id));await openEditor(o.order_id);});};content.append(form);return;}
 await openEditor(id);
}
async function openEditor(id){
 editorOrder=await api('/orders/'+encodeURIComponent(id));
 if(!currentUser.roles.some(r=>['client','manager','admin'].includes(r))){heading('Доступ ограничен');content.append(node('p','Для редактирования нужны соответствующие права на заказ.','notice'));return;}
 manualRows=[];catalogueRelease=null;
 if(editorOrder.active_revision_id){const r=await api('/orders/'+id+'/revisions/'+editorOrder.active_revision_id);catalogueRelease=r.catalogue_release_id;manualRows=r.details.filter(d=>!d.draft_row_id).map(d=>({detail_id:d.detail_id,length:d.length,width:d.width,qty:d.qty,variant_id:d.material?.variant_id||null,materialLabel:materialLabel(d.material),custom_customer:d.customer_material_key?{key:d.customer_material_key,name:d.material.name,thickness:d.material.thickness,length:d.material.length,width:d.material.width,reason:d.material.reason}:null,supply_source:d.supply_source,provided_sheets:d.provided_sheets,customer_reason:d.customer_reason,rotation:d.rotation,grain:d.grain,route:d.route,packaging:d.packaging,edges:Object.fromEntries(Object.entries(d.edges).map(([s,e])=>[s,{edge_id:e.edge?.edge_id||null,supply_source:e.supply_source}]))}));}
 dirty=false;revisionComment='';await editorView();
}
function materialLabel(m){return m?[m.manufacturer,m.raw_description||m.name,m.article,m.structure,m.thickness?m.thickness+' мм':'',m.length&&m.width?m.length+' × '+m.width+' мм':''].filter(Boolean).join(' · '):'Материал не выбран';}
async function editorView(){
 heading(editorOrder.business_name||'Деталировка','Размеры — готовые, в миллиметрах. Все расчёты выполняет сервер.');
 content.append(node('p',statusLabels[editorOrder.workflow_status]||'Статус уточняется','badge'));
 const editingAllowed=editorOrder.workflow_status==='draft'||currentUser.roles.some(r=>['admin','manager'].includes(r));
 const bar=node('div',undefined,'toolbar');bar.append(link('Заказ и документы','/account#'+editorOrder.order_id,'button secondary'));
 const add=button('Добавить деталь',()=>editRow());add.disabled=!editingAllowed;bar.append(add,button('Импорт Excel',importForm,true));
 const mode=button('Компактный / расширенный вид',()=>{content.classList.toggle('compact');},true);bar.append(mode);content.append(bar);
 if(editorOrder.preparation_mode==='manager_assisted')content.append(node('p','Загрузите исходник через проверяемый шаблон и добавьте комментарий. Не требуется самостоятельно исправлять все проблемные позиции перед передачей менеджеру.','notice'));
 renderManual();
 const draft=await api('/orders/'+editorOrder.order_id+'/draft/rows');editorOrder.optimistic_lock_version=draft.optimistic_lock_version;
 if(draft.rows.length){content.append(node('h2','Позиции из Excel'));renderImported(draft.rows);}
 if(draft.catalogue_update_available)content.append(button('Посмотреть изменения каталога',catalogueDiff,true));
 const actions=node('div',undefined,'actions');const save=button('Сохранить новую редакцию',saveRevision);save.disabled=!editingAllowed;actions.append(save);
 const calc=button('Предварительный расчёт',async()=>{if(dirty)throw new Error('Сначала сохраните новую редакцию.');await api('/orders/'+editorOrder.order_id+'/calculations','POST',{revision_id:editorOrder.active_revision_id});message('Предварительный расчёт создан. Откройте заказ и документы. Итоговая стоимость ещё не согласована.');});calc.disabled=!editorOrder.active_revision_id;actions.append(calc);content.append(actions,node('p','Сохранение новой редакции не означает согласование или запуск производства.','muted'));
 const [cl,ci]=field('Комментарий к редакции','revision_comment','textarea',revisionComment);content.append(cl);ci.oninput=()=>{dirty=true;revisionComment=ci.value;};
 if(!currentUser.roles.includes('client'))content.append(node('p','Работа с итоговым согласованием доступна только при наличии проверенного производственного расчёта.','notice'));
}
function renderManual(){const section=node('section');section.id='manual-rows';section.append(node('h2','Ручная деталировка'));
 if(!manualRows.length)section.append(node('p','Добавьте деталь или импортируйте исходный Excel.','empty'));
 else{const t=table(['№','Материал','Д × Ш, мм','Кол-во, шт.','Текстура / вращение','Кромка L1 / L2 / W1 / W2','Действия'],manualRows.map((r,i)=>[i+1,r.materialLabel,r.length+' × '+r.width,r.qty,({length:'По длине',width:'По ширине',none:'Без текстуры',unknown:'Не определена'}[r.grain])+' / '+(r.rotation?'разрешено':'запрещено'),['L1','L2','W1','W2'].map(s=>r.edges[s]?.edge_id?'Назначена':'Нет').join(' / '),'']));t.querySelectorAll('tbody tr').forEach((tr,i)=>{tr.lastChild.append(button('Изменить',()=>editRow(i),true),button('Удалить',async()=>{if(await confirmAction('Удалить деталь?','Будет удалена только строка текущей несохранённой редакции. Предыдущие редакции сохранятся.')){manualRows.splice(i,1);dirty=true;await editorView();}},true));});section.append(t);}
 const old=$('manual-rows');if(old)old.replaceWith(section);else content.append(section);
}
function picker(label,kind,release,onPick){const box=node('div'),[l,q]=field(label,'search','search'),results=node('div',undefined,'result-list'),search=button('Найти',async()=>{results.replaceChildren(node('p','Поиск…'));const d=await api('/catalogue/'+kind+'?q='+encodeURIComponent(q.value)+(release?'&release='+encodeURIComponent(release):'')+'&limit=50');results.replaceChildren();if(!d.items.length)results.append(node('p','Совпадений не найдено. Уточните артикул.'));for(const item of d.items)results.append(button(materialLabel(item),async()=>{await onPick(item,d.catalogue_release);results.replaceChildren(node('p','Выбрано: '+materialLabel(item),'selected-material'));},true));if(d.total>50)results.append(node('p','Показаны первые 50 вариантов. Уточните поиск по артикулу.'));},true);box.append(l,search,results);return box;}
async function editRow(index){
 activeRow=index;const old=manualRows[index];const r=old?structuredClone(old):{detail_id:crypto.randomUUID(),length:'',width:'',qty:1,variant_id:null,materialLabel:'Материал не выбран',supply_source:'company',rotation:false,grain:'unknown',route:'solid',packaging:false,edges:{}};
 const panel=node('section',undefined,'panel');panel.id='row-panel';panel.append(node('h2',old?'Изменить деталь':'Новая деталь'));const form=node('form',undefined,'row-editor'),grid=node('div',undefined,'grid');
 for(const [k,t]of [['length','Длина, мм'],['width','Ширина, мм'],['qty','Количество, шт.']]){const[l,i]=field(t,k,'number',r[k],true);i.min=k==='qty'?'0':'0.001';i.step=k==='qty'?'1':'0.001';grid.append(l);}
 const [gl,g]=selectField('Направление текстуры','grain',[['unknown','Не определено'],['length','По длине'],['width','По ширине'],['none','Без текстуры']],r.grain);const[rl,rot]=selectField('Вращение детали','rotation',[['false','Запрещено'],['true','Разрешено']],String(r.rotation));const[pl,route]=selectField('Конструкция','route',[['solid','Цельная плита'],['glued_18_18','Склейка 18 + 18']],r.route);const[packl,pack]=selectField('Упаковка','packaging',[['false','Без упаковки'],['true','Упаковать']],String(r.packaging));grid.append(gl,rl,pl,packl);form.append(grid);
 const selected=node('p',r.materialLabel,'selected-material');form.append(selected,picker('Поиск материала: артикул, структура','materials',catalogueRelease,async(m,release)=>{if(r.variant_id&&r.variant_id!==m.variant_id&&!await confirmAction('Заменить материал?',r.materialLabel+' → '+materialLabel(m)+'. Проверьте все ручные назначения кромки.'))return;r.variant_id=m.variant_id;r.custom_customer=null;r.materialLabel=materialLabel(m);catalogueRelease=catalogueRelease||release;selected.textContent=r.materialLabel;}));
 const [sl,supply]=selectField('Чей материал','supply_source',[['company','Материал компании'],['customer','Материал клиента']],r.supply_source);form.append(sl);const customer=node('details');customer.append(node('summary','Параметры материала клиента'));const cg=node('div',undefined,'grid');for(const[k,t,type,v]of[['provided_sheets','Передано листов, шт.','number',r.provided_sheets],['customer_reason','Основание / комментарий','text',r.customer_reason],['custom_name','Собственный материал вне каталога','text',r.custom_customer?.name],['custom_thickness','Толщина, мм','number',r.custom_customer?.thickness],['custom_length','Длина листа, мм','number',r.custom_customer?.length],['custom_width','Ширина листа, мм','number',r.custom_customer?.width]]){const[l,i]=field(t,k,type,v);if(type==='number'){i.min='0.001';i.step='0.001';}cg.append(l);}customer.append(cg);form.append(customer);
 const edges=node('fieldset');edges.append(node('legend','Кромка — четыре отдельные стороны'));
 for(const side of ['L1','L2','W1','W2']){const d=node('details');d.append(node('summary',side+' · '+(r.edges[side]?.edge_id?'Ручное назначение':'Без кромки')));const status=node('p',r.edges[side]?.edge_id?'Сохранено точное назначение':'Без кромки');d.append(status,picker('Кромка '+side,'edges',catalogueRelease,(e,release)=>{catalogueRelease=catalogueRelease||release;r.edges[side]={edge_id:e.edge_id,supply_source:'company'};status.textContent=materialLabel(e)+' · ручное назначение';d.querySelector('summary').textContent=side+' · '+(e.article||e.name||'Назначена');}),button('Без кромки',()=>{r.edges[side]={edge_id:null,supply_source:'company'};status.textContent='Без кромки';d.querySelector('summary').textContent=side+' · Без кромки';},true));const [el,es]=selectField('Источник кромки '+side,'edge_supply_'+side,[['company','Кромка компании'],['customer','Кромка клиента']],r.edges[side]?.supply_source||'company');d.append(el);edges.append(d);}
 form.append(edges,node('p','Ручные назначения не заменяются AUTO. Для импортированных строк AUTO доступен отдельно.','muted'));const actions=node('div',undefined,'actions');actions.append(node('button','Сохранить строку'),button('Отмена',()=>{panel.remove();},true));form.append(actions);
 form.onsubmit=e=>{e.preventDefault();run(async()=>{const f=new FormData(form);const qty=Number(f.get('qty'));if(!Number.isInteger(qty)||qty<1)throw new Error('Количество должно быть целым и больше нуля. Значение не исправлено автоматически.');r.length=f.get('length');r.width=f.get('width');r.qty=qty;r.grain=g.value;r.rotation=rot.value==='true';r.route=route.value;r.packaging=pack.value==='true';r.supply_source=supply.value;
 if(r.supply_source==='customer'){r.provided_sheets=Number(f.get('provided_sheets'));r.customer_reason=f.get('customer_reason');if(!Number.isInteger(r.provided_sheets)||r.provided_sheets<1||r.customer_reason.trim().length<3)throw new Error('Укажите количество листов клиента и основание.');if(f.get('custom_name')){r.variant_id=null;r.custom_customer={key:r.custom_customer?.key||crypto.randomUUID(),name:f.get('custom_name'),thickness:f.get('custom_thickness'),length:f.get('custom_length'),width:f.get('custom_width'),reason:r.customer_reason};if(['thickness','length','width'].some(k=>!(Number(r.custom_customer[k])>0)))throw new Error('Укажите толщину и формат собственного материала.');r.materialLabel=r.custom_customer.name+' · материал клиента';}}else{delete r.provided_sheets;delete r.customer_reason;r.custom_customer=null;}
 if(!r.variant_id&&!r.custom_customer)throw new Error('Выберите точный материал. Поисковая строка не является назначением.');for(const s of ['L1','L2','W1','W2'])r.edges[s]={...(r.edges[s]||{edge_id:null}),supply_source:f.get('edge_supply_'+s)};if(index===undefined)manualRows.push(r);else manualRows[index]=r;dirty=true;panel.remove();renderManual();message('Строка изменена локально. Сохраните новую редакцию заказа.');});};panel.append(form);$('row-panel')?.remove();content.append(panel);panel.scrollIntoView({block:'start'});form.querySelector('input').focus();
}
async function saveRevision(){
 if(!await confirmAction('Сохранить новую редакцию?','Будет создана отдельная редакция. Предыдущие документы и расчёты останутся неизменными.'))return;
 const details=manualRows.map(({materialLabel,...r})=>r);
 const r=await api('/orders/'+editorOrder.order_id+'/revisions','POST',{parent_revision_id:editorOrder.active_revision_id,catalogue_release_id:catalogueRelease,reason:'Сохранение деталировки пользователем',comment:revisionComment,details},{'If-Match':String(editorOrder.optimistic_lock_version)});
 editorOrder.active_revision_id=r.revision_id;editorOrder.optimistic_lock_version=r.optimistic_lock_version;dirty=false;await editorView();message('Редакция '+r.revision_number+' сохранена. Можно запросить предварительный расчёт.');
}
async function importForm(){
 const panel=node('section',undefined,'panel');panel.append(node('h2','Импорт Excel'),node('p','Исходный XLSX хранится приватно. Сначала проверьте лист и заголовки; импорт не отправляет заказ в производство.'));
 const form=node('form'),[fl,file]=field('Файл XLSX','file','file','',true);file.accept='.xlsx';const[sl,sheet]=field('Имя листа','sheet','text','Лист1',true),[tl,templateId]=field('ID сохранённой версии шаблона (если есть)','template');
 const mapping=node('details');mapping.open=true;mapping.append(node('summary','Сопоставление колонок нового шаблона'));
 const mg=node('div',undefined,'grid'),fields=[['length','Длина'],['width','Ширина'],['qty','Количество'],['article','Артикул'],['material','Материал'],['L1','L1'],['L2','L2'],['W1','W1'],['W2','W2'],['texture','Текстура'],['rotation','Вращение']];
 fields.forEach(([k,label],i)=>{const[l,c]=field(label+': буква колонки','col_'+k,'text',String.fromCharCode(65+i));c.maxLength=3;const[hl,h]=field(label+': точный заголовок','header_'+k,'text',label);mg.append(l,hl);});mapping.append(node('p','Укажите фактические заголовки первой строки. Пустая буква исключает необязательное поле. X1/X2/Y1/Y2 сопоставляйте с L1/L2/W1/W2 явно.','muted'),mg);
 const [ul,units]=selectField('Единицы длины и ширины','units',[['mm','мм'],['cm','см'],['m','м']],'mm');form.append(fl,sl,tl,mapping,ul,node('button','Проверить файл'));panel.append(form);content.append(panel);file.focus();
 form.onsubmit=e=>{e.preventDefault();run(async()=>{if(file.files[0].size>20*1024*1024)throw new Error('Файл превышает 20 МБ.');let tid=templateId.value.trim();if(!tid){const headers={},map={};const f=new FormData(form);for(const[k]of fields){const col=String(f.get('col_'+k)).trim().toUpperCase();if(col){if(!/^[A-Z]{1,3}$/.test(col))throw new Error('Колонки задаются буквами A, B, C…');map[k]=col;headers[col]=f.get('header_'+k);}}const t=await api('/import-templates','POST',{name:'Шаблон '+file.files[0].name.slice(0,65),order_id:editorOrder.order_id,definition:{headers,sheet_policy:{mode:'named',header_row:1,sheets:[sheet.value]},mapping:map,inheritance:{enabled:false,blank_resets:true},edge_dictionary:{'0':'none','нет':'none','no':'none','false':'none','-':'none','*':'present','1':'present','':'unknown'},units:{length:units.value,width:units.value}}});tid=t.template_revision_id;templateId.value=tid;}
 const bytes=new Uint8Array(await file.files[0].arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const r=await api('/imports/preview','POST',{filename:file.files[0].name,content_base64:btoa(binary),order_id:editorOrder.order_id,template_revision_id:tid,selected_sheets:[sheet.value],catalogue_release:catalogueRelease});importId=r.import_id;const result=node('div');result.append(node('h3','Предпросмотр — строки не потеряны'));const rows=r.rows||[];result.append(table(['Лист / строка','Тип','Длина','Ширина','Количество','Ошибки'],rows.map(row=>{const o=row.original||row;return [o.sheet+' / '+o.row,o.disposition,o.values?.length,o.values?.width,o.values?.qty,(o.errors||[]).map(x=>x.field+': '+x.reason).join('; ')];})),node('p','Нулевые количества и другие ошибки сохранены для явного исправления или передачи менеджеру.','notice'));result.append(button('Добавить позиции в черновик',async()=>{if(!await confirmAction('Добавить импорт?', 'Существующие позиции сохранятся. Ошибочные строки не будут автоматически исправлены.'))return;const o=await api('/orders/'+editorOrder.order_id);await api('/imports/'+importId+'/confirm','POST',{mode:'add'},{'If-Match':String(o.optimistic_lock_version)});await editorView();message('Импорт добавлен. Проверьте назначения материала и кромки.');}));panel.append(result);result.scrollIntoView();});};
}
function renderImported(rows){
 const t=table(['Строка','Материал / статус','Д × Ш, мм','Количество','Ошибки / исключение','Действия'],rows.map(r=>{const s=r.snapshot,v=s.values||{},res=s.resolution||{};return[v.position??s.row,materialLabel(res.selected)+' / '+({exact_match:'Точное совпадение',manual_override:'Выбрано вручную',confirmed_mapping:'Подтверждено',ambiguous:'Нужно уточнение',not_found:'Не найдено',custom_customer:'Материал клиента'}[res.status]||'Требует проверки'),value(v.length)+' × '+value(v.width),v.qty,r.excluded_reason||((s.errors||[]).map(e=>e.field+': '+e.reason).join('; ')||'Нет ошибок исходных значений'),''];}));
 t.querySelectorAll('tbody tr').forEach((tr,i)=>{const r=rows[i];if(r.excluded_reason)return;tr.lastChild.append(button('Материал / кромка',()=>importedEditor(r),true),button('Исключить',async()=>{const reason=await reasonDialog('Исключить строку','Строка сохранится в истории с указанной причиной.');if(!reason)return;const result=await api('/orders/'+editorOrder.order_id+'/draft/rows/'+r.draft_row_id+'/exclude','POST',{reason},{'If-Match':String(editorOrder.optimistic_lock_version)});editorOrder.optimistic_lock_version=result.optimistic_lock_version;await editorView();},true));});content.append(t);
}
function reasonDialog(title,text){return new Promise(resolve=>{const d=node('dialog'),form=node('form'),[l,i]=field('Причина','reason','textarea','',true);i.minLength=3;i.maxLength=500;form.append(node('h2',title),node('p',text),l,node('button','Подтвердить'));const no=node('button','Отмена','secondary');no.type='button';form.append(no);const end=v=>{d.close();d.remove();resolve(v);};no.onclick=()=>end(null);form.onsubmit=e=>{e.preventDefault();end(i.value);};d.oncancel=e=>{e.preventDefault();end(null);};d.append(form);document.body.append(d);d.showModal();i.focus();});}
async function importedEditor(r){const p=node('section',undefined,'panel');p.append(node('h2','Назначения импортированной строки'));
 const base='/orders/'+editorOrder.order_id+'/draft/rows/'+r.draft_row_id;
 async function mutate(url,body){const result=await api(base+url,'POST',body,{'If-Match':String(editorOrder.optimistic_lock_version)});editorOrder.optimistic_lock_version=result.optimistic_lock_version;dirty=true;await editorView();message('Назначение сохранено в черновике. Создайте новую редакцию для расчёта.');}
 p.append(picker('Точный материал','materials',r.release_id,async(m)=>{const reason=await reasonDialog('Изменить материал','Новый материал: '+materialLabel(m)+'. AUTO будет проверен сервером, ручная кромка сохраняется.');if(reason)await mutate('/material',{variant_id:m.variant_id,reason});}));
 for(const side of ['L1','L2','W1','W2']){const d=node('details'),e=r.snapshot.edges?.[side];d.append(node('summary',side+' · '+({manual_override:'Ручное назначение',auto_suggestion:'Предложение AUTO',confirmed_mapping:'Подтверждено'}[e?.mode]||'Требует проверки')),node('p',e?.snapshot?materialLabel(e.snapshot):'Назначение отсутствует или требует подтверждения'),picker('Кромка '+side,'edges',r.release_id,async(edge)=>{const reason=await reasonDialog('Назначить кромку '+side,materialLabel(edge));if(reason)await mutate('/edges',{side,action:'manual',edge_id:edge.edge_id,reason});}),button('Без кромки '+side,async()=>{const reason=await reasonDialog('Убрать кромку '+side,'Будет сохранено явное ручное отсутствие кромки.');if(reason)await mutate('/edges',{side,action:'manual',edge_id:null,reason});},true),button('Сбросить '+side+' в AUTO',async()=>{const reason=await reasonDialog('Сбросить ручное назначение?',side+': ручное назначение будет снято только после вашего подтверждения.');if(reason)await mutate('/edges',{side,action:'reset_auto',reason});},true));p.append(d);}
 content.append(p);p.scrollIntoView();}
async function catalogueDiff(){const result=await api('/orders/'+editorOrder.order_id+'/draft/catalogue-update');const p=node('section',undefined,'panel');p.append(node('h2','Изменения каталога'),table(['Позиция','Точный вариант доступен','Ручная кромка'],result.diff.map((d,i)=>[i+1,d.variant_available?'Да':'Нет — сохранить закреплённый вариант',d.manual_edges_preserved?'Сохраняется':'Требует проверки'])),node('p','AUTO будет проверен заново. Ручные назначения сохраняются.','notice'),button('Применить к черновику',async()=>{const reason=await reasonDialog('Обновить каталог черновика?','Ранее созданные редакции, расчёты и документы не изменятся.');if(!reason)return;await api('/orders/'+editorOrder.order_id+'/draft/catalogue-update','POST',{release_id:result.release_id,reason},{'If-Match':String(editorOrder.optimistic_lock_version)});await editorView();}));content.append(p);}
async function staffHome(){
 if(currentUser.roles.includes('client')||currentUser.roles.includes('service_agent')){heading('Доступ ограничен');content.append(node('p','Рабочий кабинет доступен сотрудникам с соответствующими правами.','notice'),link('Мои заказы','/account','button'));return;}
 heading('Рабочий кабинет','Показываются только заказы, доступные по вашим текущим правам.');const tabs=node('div',undefined,'staff-tabs');tabs.append(button('Очередь заказов',staffQueue,true));if(currentUser.roles.includes('admin'))tabs.append(button('Сотрудники',staffList,true),button('Журнал действий',auditList,true),button('Каталог',catalogueView,true),button('Тарифы и профили',financialView,true));content.append(tabs);const area=node('div');area.id='staff-content';content.append(area);await staffQueue();
}
async function staffQueue(after='',append=false){const area=$('staff-content'),d=await api('/orders?after='+encodeURIComponent(after));if(!append)area.replaceChildren(node('h2','Очередь заказов'));if(!d.items.length&&!append)area.append(node('p','Доступных заказов пока нет.','empty'));for(const o of d.items){const a=node('article',undefined,'order');a.append(node('h3',o.business_name||'Заказ'),node('p',statusLabels[o.workflow_status]||'Статус уточняется'));if(currentUser.roles.some(r=>['manager','admin'].includes(r)))a.append(link('Открыть деталировку','/editor?order='+encodeURIComponent(o.order_id),'button secondary'));if(o.workflow_status==='submitted'&&currentUser.roles.some(r=>['manager','admin'].includes(r)))a.append(button('Взять на проверку',async()=>{const reason=await reasonDialog('Начать проверку заказа?',o.business_name||'Заказ');if(!reason)return;await api('/orders/'+o.order_id+'/review','POST',{reason},{'If-Match':String(o.optimistic_lock_version)});await staffQueue();}));if(currentUser.roles.includes('admin'))a.append(button('Назначить менеджера',()=>assignmentForm(o),true));area.append(a);}if(d.next){const more=button('Показать ещё',async()=>{more.remove();await staffQueue(d.next,true);},true);area.append(more);}}
async function assignmentForm(order){const staff=await api('/admin/staff'),area=$('staff-content'),form=node('form',undefined,'panel');const[l,s]=selectField('Менеджер','manager_id',[['','Без менеджера'],...staff.items.filter(u=>u.role==='manager'&&u.account_status==='active').map(u=>[u.user_id,u.email])],order.assigned_manager_id||'');const[rl,r]=field('Причина назначения','reason','text','',true);r.minLength=3;form.append(node('h2','Назначение менеджера'),l,rl,node('button','Сохранить назначение'));form.onsubmit=e=>{e.preventDefault();run(async()=>{await api('/orders/'+order.order_id+'/assign-manager','POST',{manager_id:s.value||null,reason:r.value});await staffQueue();message('Назначение сохранено.');});};area.append(form);}
async function staffList(){const d=await api('/admin/staff'),area=$('staff-content');area.replaceChildren(node('h2','Сотрудники'),node('p','Роль ограничивает доступ; отдельные разрешения проверяются сервером.','muted'));const t=table(['Email','Роль','Состояние','Управление'],d.items.map(u=>[u.email,u.role,u.account_status==='active'?'Активен':'Заблокирован','']));t.querySelectorAll('tbody tr').forEach((tr,i)=>{const u=d.items[i];tr.lastChild.append(button(u.account_status==='active'?'Заблокировать':'Разблокировать',async()=>{const blocked=u.account_status==='active';if(!await confirmAction(blocked?'Заблокировать сотрудника?':'Разблокировать сотрудника?',u.email+(blocked?'. Активные сессии будут отозваны.':'. Выданные права будут проверяться заново.')))return;await api('/admin/staff/'+u.user_id+'/state','PUT',{status:blocked?'blocked':'active'});await staffList();},true),button('Роль и разрешения',()=>grantForm(u),true));});area.append(t,button('Добавить сотрудника',staffCreate,true));}
async function staffCreate(){const f=node('form',undefined,'panel');const[el,email]=field('Email сотрудника','email','email','',true),[pl,password]=field('Временный пароль (от 12 символов)','password','password','',true);password.minLength=12;password.autocomplete='new-password';const[rl,role]=selectField('Роль','role',['manager','production','accounting','viewer','admin'].map(x=>[x,x]));f.append(node('h2','Новый сотрудник'),el,pl,rl,node('button','Создать сотрудника'));f.onsubmit=e=>{e.preventDefault();run(async()=>{await api('/admin/staff','POST',{email:email.value,password:password.value,role:role.value});password.value='';await staffList();message('Сотрудник создан. Разрешения выдаются отдельно.');});};$('staff-content').append(f);}
async function grantForm(user){const f=node('form',undefined,'panel');const[pl,p]=field('Точное разрешение (без *)','permission','text','',true),[sl,s]=selectField('Область доступа','scope',[['assigned','Назначенные заказы'],['order','Конкретный заказ'],['job','Конкретное производственное задание']]),[il,id]=field('ID области (для конкретного объекта)','scope_id');const[rl,role]=selectField('Роль сотрудника','role',['manager','production','accounting','viewer','admin'].map(x=>[x,x]),user.role);f.append(node('h2','Доступ: '+user.email),rl,button('Изменить роль',async()=>{if(await confirmAction('Изменить роль сотрудника?',user.role+' → '+role.value)){await api('/admin/staff/'+user.user_id+'/role','PUT',{role:role.value});await staffList();}},true),pl,sl,il,node('button','Выдать точное разрешение'));f.onsubmit=e=>{e.preventDefault();run(async()=>{if(p.value.includes('*'))throw new Error('Wildcard-разрешения запрещены.');if(!await confirmAction('Выдать разрешение?',p.value+' / '+s.value))return;await api('/admin/staff/'+user.user_id+'/grants','POST',{permission:p.value,scope_type:s.value,scope_id:id.value||null});message('Разрешение сохранено.');});};$('staff-content').append(f);}
async function auditList(){const d=await api('/admin/audit');$('staff-content').replaceChildren(node('h2','Журнал действий'),table(['Дата','Действие','Объект'],d.items.map(e=>[date(e.created_at),e.action,e.object_type])));}
async function catalogueView(){const d=await api('/catalogue/releases'),area=$('staff-content');area.replaceChildren(node('h2','Каталог'),node('p','Материал выбирается по точной идентичности. Поиск не меняет назначения в заказах.'));area.append(picker('Найти материал','materials',d.active_release,(m)=>message(materialLabel(m))),table(['Релиз','Дата','Состояние'],d.items.map(r=>[r.release_id,date(r.created_at),r.release_id===d.active_release?'Активный':'Архивный'])));}
async function financialView(){const d=await api('/financial/defaults');$('staff-content').replaceChildren(node('h2','Действующие версии расчёта'),node('p','Публикация новых цен и тарифов не входит в изменение дизайна. Старые расчёты используют закреплённые версии.','notice'),table(['Профиль','Версия'],[['Производственный профиль',d.production_profile_id],['Тарифы',d.tariff_book_id],['Цены',d.price_book_id],['Скидки',d.discount_profile_id]]));}
